from django.db import models

DATABASE = {'1': {'name': 'Bell Pepper',
                  'discount': 30,
                  'price_before': 120.00,
                  'price_after': 80.00,
                  'id': 1,
                  'url': 'store/images/product-1.jpg'},
            '2': {'name': 'Strawberry',
                  'discount': None,
                  'price_before': 120.00,
                  'id': 2,
                  'url': 'store/images/product-2.jpg'},
            '3': {'name': 'Green Beans',
                  'discount': None,
                  'price_before': 120.00,
                  'id': 3,
                  'url': 'store/images/product-3.jpg'},
            '4': {'name': 'Purple Cabbage',
                  'discount': None,
                  'price_before': 120.00,
                  'id': 4,
                  'url': 'store/images/product-4.jpg'},
            '5': {'name': 'Tomatoe',
                  'discount': 30,
                  'price_before': 120.00,
                  'price_after': 80.00,
                  'id': 5,
                  'url': 'store/images/product-5.jpg'},
            '6': {'name': 'Brocolli',
                  'discount': None,
                  'price_before': 120.00,
                  'id': 6,
                  'url': 'store/images/product-6.jpg'},
            '7': {'name': 'Carrots',
                  'discount': None,
                  'price_before': 120.00,
                  'id': 7,
                  'url': 'store/images/product-7.jpg'},
            '8': {'name': 'Fruit Juice',
                  'discount': None,
                  'price_before': 120.00,
                  'id': 8,
                  'url': 'store/images/product-8.jpg'},
            '9': {'name': 'Onion',
                  'discount': 30,
                  'price_before': 120.00,
                  'price_after': 80.00,
                  'id': 9,
                  'url': 'store/images/product-9.jpg'},
            '10': {'name': 'Apple',
                   'discount': None,
                   'price_before': 120.00,
                   'id': 10,
                   'url': 'store/images/product-10.jpg'},
            '11': {'name': 'Garlic',
                   'discount': None,
                   'price_before': 120.00,
                   'id': 11,
                   'url': 'store/images/product-11.jpg'},
            '12': {'name': 'Chilli',
                   'discount': None,
                   'price_before': 120.00,
                   'id': 12,
                   'url': 'store/images/product-12.jpg'},
            }
