from django.db import models

DATABASE = {'1': {'name': 'Болгарский перец',
                  'discount': 30,
                  'price_before': 120.00,
                  'price_after': 80.00,
                  'description': 'Сочный и яркий, он добавит красок и вкуса в ваши блюда.',
                  'category': 'Овощи',
                  'id': 1,
                  'url': 'store/images/product-1.jpg'},
            '2': {'name': 'Клубника',
                  'discount': None,
                  'price_before': 120.00,
                  'description': 'Сладкая и ароматная клубника, полная витаминов, чтобы сделать ваш день ярче.',
                  'category': 'Фрукты',
                  'id': 2,
                  'url': 'store/images/product-2.jpg'},
            '3': {'name': 'Стручковая фасоль',
                  'discount': None,
                  'price_before': 120.00,
                  'description': 'Зеленая натуральность и богатство белка для вашей здоровой диеты.',
                  'category': 'Овощи',
                  'id': 3,
                  'url': 'store/images/product-3.jpg'},
            '4': {'name': 'Фиолетовая капуста',
                  'discount': None,
                  'price_before': 120.00,
                  'description': 'Удивите своих гостей экзотическим вкусом и цветом ваших блюд.',
                  'category': 'Овощи',
                  'id': 4,
                  'url': 'store/images/product-4.jpg'},
            '5': {'name': 'Помидоры',
                  'discount': 30,
                  'price_before': 120.00,
                  'price_after': 80.00,
                  'description': 'Свежие и сочные помидоры для идеальных салатов и соусов.',
                  'category': 'Овощи',
                  'id': 5,
                  'url': 'store/images/product-5.jpg'},
            '6': {'name': 'Брокколи',
                  'discount': None,
                  'price_before': 120.00,
                  'description': 'Здоровье в каждом кусочке, чтобы укрепить вашу иммунную систему.',
                  'category': 'Овощи',
                  'id': 6,
                  'url': 'store/images/product-6.jpg'},
            '7': {'name': 'Морковь',
                  'discount': None,
                  'price_before': 120.00,
                  'description': 'Красота и здоровье для ваших глаз и кожи в каждой моркови.',
                  'category': 'Овощи',
                  'id': 7,
                  'url': 'store/images/product-7.jpg'},
            '8': {'name': 'Фруктовый сок',
                  'discount': None,
                  'price_before': 120.00,
                  'description': 'Натуральная свежесть и энергия в каждом глотке.',
                  'category': 'Соки',
                  'id': 8,
                  'url': 'store/images/product-8.jpg'},
            '9': {'name': 'Лук',
                  'discount': 30,
                  'price_before': 120.00,
                  'price_after': 80.00,
                  'description': 'Придайте особый аромат и вкус вашим блюдам с нашим свежим луком.',
                  'category': 'Овощи',
                  'id': 9,
                  'url': 'store/images/product-9.jpg'},
            '10': {'name': 'Яблоки',
                   'discount': None,
                   'price_before': 120.00,
                   'description': 'Сочные и сладкие яблоки - идеальная закуска для здорового перекуса.',
                   'category': 'Фрукты',
                   'id': 10,
                   'url': 'store/images/product-10.jpg'},
            '11': {'name': 'Чеснок',
                   'discount': None,
                   'price_before': 120.00,
                   'description': 'Секрет вкусных блюд и поддержания здоровья вашего сердца.',
                   'category': 'Овощи',
                   'id': 11,
                   'url': 'store/images/product-11.jpg'},
            '12': {'name': 'Перец Чили',
                   'discount': None,
                   'price_before': 120.00,
                   'description': 'Острая страсть для тех, кто ищет приключения на своей тарелке.',
                   'category': 'Овощи',
                   'id': 12,
                   'url': 'store/images/product-12.jpg'},
            }
